working endpoint
momentum-pt-team-1/final-project pull request #9
Opened 2021-08-30 15:38 UTC by allisondurham

for testing this:

$>  python manage.py runserver
command click local server link

feel free to add test pieces in the admin

http://127.0.0.1:8000/api/places/         for all works

for any work in your database, visit /api/places/[id#]       for example:
http://127.0.0.1:8000/api/places/2/      for work #2, change integer for relevant piece

you are expecting to see a json response with all the fields and their corresponding data for either a list of all works, or a single specific one

2021-08-30 16:02 UTC, KimWheaton requested changes
Thanks, Allison. This looks really good. There are just two small changes. 
Also there needs to be an Artist class endpoint and Artist in the Work serializer.

2021-08-30 16:02 UTC, KimWheaton commented on durham/settings.py
> +    # 'places.apps.PlacesConfig'
You can remove this because you don't need both.

2021-08-30 16:02 UTC, KimWheaton commented on places/serializers.py
> +# class WorkSerializer(serializers.Serializer):
You can remove this code.

2021-08-31 14:11 UTC, allisondurham commented on durham/settings.py
> +    # 'places.apps.PlacesConfig'
done, removed commented out code

2021-08-31 21:43 UTC, allisondurham commented on places/serializers.py
> +# class WorkSerializer(serializers.Serializer):
done!

2021-08-31 21:44 UTC, allisondurham commented
I believe I addressed the requested changes

2021-09-02 14:23 UTC, KimWheaton approved these changes

2021-09-02 14:35 UTC, KimWheaton commented
🦦

2021-09-02 14:36 UTC, merged

2021-09-02 14:36 UTC, KimWheaton commented
🦦